### ISSUE TITLE
Use earthkit-data instead of climetlab

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/anemoi-datasets#2]
Work in progress. Needs: 
-  `earthkit-data>0.8.1`
-  `earthkit-geo>=0.2.0`

Current status (on a MacBook): 
- initial conversion done 
- all the tests pass
- dataset creation with the 3 recipes at https://anemoi-datasets.readthedocs.io/en/latest/building/introduction.html#getting-started works
- tested configs (with reduced data):
   -  [aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v1-precipitations.yaml](https://github.com/ecmwf-lab/anemoi-datasets-configs/blob/main/datasets/aifs-od-an-oper-0001-mars-o96-2016-2023-6h-v1-precipitations.yaml)
   -  [aifs-od-an-elda-0001-mars-o96-2016-2023-6h-v2-recentered-on-oper.yaml](https://github.com/ecmwf-lab/anemoi-datasets-configs/blob/main/datasets/ensembles/aifs-od-an-elda-0001-mars-o96-2016-2023-6h-v2-recentered-on-oper.yaml)
   - [aifs-ea-an-oper-0001-mars-n320-2020-2023-6h-v2-metno-bc-rotated.yaml](https://github.com/ecmwf-lab/anemoi-datasets-configs/blob/main/datasets/aifs-ea-an-oper-0001-mars-n320-2020-2023-6h-v2-metno-bc-rotated.yaml)
   - [metno-meps-archive-det-opendap-2p5km-2020-2023-6h-v1.yaml](https://github.com/ecmwf-lab/anemoi-datasets-configs/blob/main/datasets/metno-meps-archive-det-opendap-2p5km-2020-2023-6h-v1.yaml)
   - [aifs-o6-tpa-ocda-0001-mars-o96-2005-2016-24h-v1-ocean-surface.yaml](https://github.com/ecmwf-lab/anemoi-datasets-configs/blob/main/datasets/aifs-o6-tpa-ocda-0001-mars-o96-2005-2016-24h-v1-ocean-surface.yaml)
   - aifs-ea-an-oper-0001-mars-o96-1979-2023-6h-v1-snowfall.yaml
   - cerra-rr-an-oper-0001-mars-5p5km-1984-2008-6h-v1-hmsi.yaml

**Comment by b8raoult** [comment]
Done in version 0.4.0
