### ISSUE TITLE
add a flag to disable computing statistics tendencies

### ISSUE THREAD

**Issue by floriankrb** [ecmwf/anemoi-datasets#21]
Should we have a flag to disable the computation of statistics_tendencies_* during building a dataset?

**Comment by mpvginde** [comment]
Another option could be to allow for the delta's of the `additions` to be specified in the config file?

**Comment by floriankrb** [comment]
Anemoi-datasets can now create datasets incrementally https://anemoi-datasets.readthedocs.io/en/latest/building/incremental.html. 
This is the recommended way to build datasets without the statistics tendencies.
