### ISSUE TITLE
Dependency on met.no opendap make the tests fails.

### ISSUE THREAD

**Issue by floriankrb** [ecmwf/anemoi-datasets#47]
Seing here https://github.com/ecmwf/anemoi-datasets/actions/runs/10907013942/job/30269681465

The tests are failing because 'https://thredds.met.no/thredds/dodsC/meps25epsarchive/2023/01/01/meps_det_2_5km_20230101T00Z.nc' is not here anymore, or not accessible.

There is no impact on the anemoi-datasets features/quality.

In theory, the anemoi-datasets should not rely on this external source to do unit testing, and a good way to fix this is to make a copy on nexus, but this is actually testing opendap so we may want another opendap server, locally. Or on the EWC. Or use pytest mockup, or monkey patching, but carefully. Anyways, fixing this would take time.

I suggest we reach met.no to see if this file has moved, @mchantry do you want to raise the issue at the working group?

**Comment by floriankrb** [comment]
As this failing test breaks the ci of other ecmwf software, we may need another temporary solution (a quick commit to develop and main to disable the test would be easy to do).

**Comment by shahramn** [comment]
Many thanks

**Comment by floriankrb** [comment]
[meps_det_2_5km_small_20230101T00Z.nc.remove-extension.txt](https://github.com/user-attachments/files/17094658/meps_det_2_5km_small_20230101T00Z.nc.remove-extension.txt)

The failing test was due to maintenance of the opendap server, it is fixed now.

We could refactor the tests to:
- Test directly the file format from metno (attaching a test file to use in the tests)
- Test on a stable opendap (but we don't want to test opendap, having well designed mockups test could be better).
