### ISSUE TITLE
Anemoi-datasets copy from s3 bucket deletes current folder

### ISSUE THREAD

**Issue by einrone** [ecmwf/anemoi-datasets#88]
**Describe the bug**

When running for example :

anemoi-datasets copy s3://ml-datasets/aifs-ea-an-enda-0001-mars-o96-1979-2022-6h-v6-recentered-on-oper.zarr .

It deletes the current folder I am inside (i.e the ".")

**To Reproduce**

**URL to sample input data**
Provide a URL to a sample input data, or attach a file to that report if it is small enough.

**Expected behavior**

I expected that it will copy a given zarr dataset to my folder and not delete everything that is inside. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

using ubuntu

**Additional context**

**Comment by floriankrb** [comment]
This should be fixed in the current `develop` branch. Could you confirm, please?

**Comment by einrone** [comment]
Hi florian, apologize for the delay. Yes I did conduct a fast test with 

anemoi-datasets copy s3://ml-datasets/aifs-od-an-oper-0001-mars-o96-2021-6h-v2.zarr .

And indeed now it does not delete the files in the folder where anemoi-datasets copy is executed.
